// Age-appropriate word database for 6-year-olds
const wordDatabase = [
    { word: 'cat', emoji: '🐱', hint: 'Starts with C, ends with T' },
    { word: 'dog', emoji: '🐶', hint: 'Starts with D, ends with G' },
    { word: 'sun', emoji: '☀️', hint: 'Starts with S, ends with N' },
    { word: 'moon', emoji: '🌙', hint: 'Starts with M, ends with N' },
    { word: 'star', emoji: '⭐', hint: 'Starts with S, ends with R' },
    { word: 'tree', emoji: '🌳', hint: 'Starts with T, ends with E' },
    { word: 'bird', emoji: '🐦', hint: 'Starts with B, ends with D' },
    { word: 'fish', emoji: '🐟', hint: 'Starts with F, ends with H' },
    { word: 'book', emoji: '📚', hint: 'Starts with B, ends with K' },
    { word: 'ball', emoji: '⚽', hint: 'Starts with B, ends with L' },
    { word: 'car', emoji: '🚗', hint: 'Starts with C, ends with R' },
    { word: 'house', emoji: '🏠', hint: 'Starts with H, ends with E' },
    { word: 'apple', emoji: '🍎', hint: 'Starts with A, ends with E' },
    { word: 'banana', emoji: '🍌', hint: 'Starts with B, ends with A' },
    { word: 'cake', emoji: '🎂', hint: 'Starts with C, ends with E' },
    { word: 'water', emoji: '💧', hint: 'Starts with W, ends with R' },
    { word: 'flower', emoji: '🌸', hint: 'Starts with F, ends with R' },
    { word: 'rain', emoji: '🌧️', hint: 'Starts with R, ends with N' },
    { word: 'snow', emoji: '❄️', hint: 'Starts with S, ends with W' },
    { word: 'cloud', emoji: '☁️', hint: 'Starts with C, ends with D' },
    { word: 'heart', emoji: '❤️', hint: 'Starts with H, ends with T' },
    { word: 'smile', emoji: '😊', hint: 'Starts with S, ends with E' },
    { word: 'friend', emoji: '👫', hint: 'Starts with F, ends with D' },
    { word: 'happy', emoji: '😄', hint: 'Starts with H, ends with Y' },
    { word: 'play', emoji: '🎮', hint: 'Starts with P, ends with Y' },
    { word: 'jump', emoji: '🦘', hint: 'Starts with J, ends with P' },
    { word: 'run', emoji: '🏃', hint: 'Starts with R, ends with N' },
    { word: 'sing', emoji: '🎵', hint: 'Starts with S, ends with G' },
    { word: 'dance', emoji: '💃', hint: 'Starts with D, ends with E' },
    { word: 'sleep', emoji: '😴', hint: 'Starts with S, ends with P' },
    { word: 'eat', emoji: '🍽️', hint: 'Starts with E, ends with T' },
    { word: 'drink', emoji: '🥤', hint: 'Starts with D, ends with K' },
    { word: 'red', emoji: '🔴', hint: 'Starts with R, ends with D' },
    { word: 'blue', emoji: '🔵', hint: 'Starts with B, ends with E' },
    { word: 'green', emoji: '🟢', hint: 'Starts with G, ends with N' },
    { word: 'yellow', emoji: '🟡', hint: 'Starts with Y, ends with W' },
    { word: 'orange', emoji: '🟠', hint: 'Starts with O, ends with E' },
    { word: 'purple', emoji: '🟣', hint: 'Starts with P, ends with E' },
    { word: 'pink', emoji: '💗', hint: 'Starts with P, ends with K' },
    { word: 'one', emoji: '1️⃣', hint: 'Starts with O, ends with E' },
    { word: 'two', emoji: '2️⃣', hint: 'Starts with T, ends with O' },
    { word: 'three', emoji: '3️⃣', hint: 'Starts with T, ends with E' },
    { word: 'four', emoji: '4️⃣', hint: 'Starts with F, ends with R' },
    { word: 'five', emoji: '5️⃣', hint: 'Starts with F, ends with E' },
    { word: 'big', emoji: '📏', hint: 'Starts with B, ends with G' },
    { word: 'small', emoji: '📐', hint: 'Starts with S, ends with L' },
    { word: 'hot', emoji: '🔥', hint: 'Starts with H, ends with T' },
    { word: 'cold', emoji: '🧊', hint: 'Starts with C, ends with D' },
    { word: 'up', emoji: '⬆️', hint: 'Starts with U, ends with P' },
    { word: 'down', emoji: '⬇️', hint: 'Starts with D, ends with N' },
    { word: 'yes', emoji: '✅', hint: 'Starts with Y, ends with S' },
    { word: 'no', emoji: '❌', hint: 'Starts with N, ends with O' }
];

